// SIGN UP
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
// LOG IN
export const LOG_IN_START = 'LOG_IN_START';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
// INTERACTIONS
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_SEARCH_NAME_PARAM = 'SET_SEARCH_NAME_PARAM';
export const SET_SEARCH_TITLE_PARAM = 'SET_SEARCH_TITLE_PARAM';

// GET EXPERTS
export const GET_ALL_EXPERTS = 'GET_ALL_EXPERTS';
// GET PENDING REQUESTS
export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS';

// CONNECT WITH EXPERT
export const CONNECT_TO_EXPERT = 'CONNECT_WITH_EXPERT';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
